source 'https://rubygems.org'

gem 'RedCloth', '4.2.9'
gem 'activeadmin', '~> 0.5.0'
gem 'bb-ruby', '0.9.5'
gem 'cancan', '1.6.8'
gem 'carrierwave', '0.7.1'
gem 'client_side_validations'
gem 'coderay', '~> 1.0.6'
gem 'compass-rails'
gem 'devise', '~> 2.2.3'
gem 'escape_utils', '0.2.3'
gem 'fog', '~> 1.4.0'
gem 'friendly_id', '~> 4.0.1'
gem 'gravtastic', '3.1.0'
gem 'griddler', '~> 0.3.0'
gem 'highline', '1.6.1'
gem 'htmlentities'
gem 'kaminari', '0.13.0'
gem 'mini_magick', '3.2.1'
gem 'multi_json'
gem 'nested_form', '~> 0.2.0'
gem 'nokogiri', '1.5.0'
gem 'omniauth-github'
gem 'pseudohelp'
gem 'pg'
gem 'rack'
gem 'rails', '3.2.13'
gem 'rails_emoji', '~> 1.5'
gem 'rake', '0.9.2.2'
gem 'redcarpet', '~> 2.1.1'
gem 'rspec-rails', '~> 2.12.2'
gem 'thin'

group :assets do
  gem 'chosen.scss', '1.0.8', require: 'chosen.scss'
  gem 'coffee-rails', '~> 3.2.2'
  gem 'font-icons', '~> 1.0.3.beta', require: 'font-icons'
  gem 'jquery-rails'
  gem 'sass', '3.2.1'
  gem 'sass-rails', '3.2.5'
  gem 'therubyracer'
  gem 'uglifier'
end

group :test, :cucumber do
  gem 'addressable', '~> 2.3.2'
  gem 'bourne'
  gem 'capybara', '~> 2.0.2'
  gem 'chronic'
  gem 'cucumber-rails', '~> 1.3.0', require: false
  gem 'database_cleaner'
  gem 'email_spec', '1.4.0'
  gem 'factory_girl_rails', '~> 4.1.0'
  gem 'fuubar'
  gem 'launchy', '~> 2.1.2'
  gem 'pry'
  gem 'rack-test', '0.6.1'
  gem 'rb-fsevent'
  gem 'shoulda-matchers', '1.2.0'
  gem 'timecop'
end

group :development do
  gem 'faker'
  gem 'git_remote_branch'
  gem 'hub'
  gem 'letter_opener'
  gem 'pry'
  gem 'sextant'
  gem 'zeus'
end
